/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cT6p2S217fw
*/

import * as React from "react"
import { Button } from "@/components/ui/button"
import { ModeToggle } from "@/components/mode-toggle"
import { cn } from "@/lib/utils"

import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"
import ilustracion from "@/assets/ilustracion.png"
import ilustracionMobile from "@/assets/ilustracionMobile.png"
import MenuIcon from '@mui/icons-material/Menu';
import CloseIcon from '@mui/icons-material/Close';

export function Navbar() {
  const [open, setIsOpen] = React.useState(false)
  return (
    <header className="flex items-center h-16 px-4 md:px-6 w-full">
      <a className="mr-4" href="#">
        <span className="absolute text-2xl top-[20px]">NxSoft</span>
      </a>
      <nav className={`flex-1 ${open ? "left-[-30px] w-full  justify-start items-start  " : "left-[-400px]"} relative flex-col flex md:flex-row md:left-0 md:top-0 md:justify-center md:dark:bg-transparent md:bg-transparent  transition-all dark:bg-[#34405e] bg-[#6c758b] dark:text-white text-black  top-40 gap-4 py-12 px-6  md:flex items-center justify-center`}>
        <a
          className="font-semibold inline-flex h-8 items-center justify-center px-2.5 rounded-md text-sm transition-colors hover:text-gray-900 dark:hover:text-gray-50"
          href="#"
        >
          Inicio
        </a>
        <a className="inline-flex h-8 items-center justify-center mx-2 rounded-md text-sm" href="#pricing">
          Precios
        </a>
        <NavigationMenu className="z-50">
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuTrigger>Planes</NavigationMenuTrigger>
              <NavigationMenuContent>
                <ul className="grid gap-3 p-6 w-full md:w-[400px] lg:w-[500px] grid-cols-[.75fr_1fr]">
                  <li className="row-span-3">
                    <NavigationMenuLink asChild>
                      <a
                        className="flex h-auto md:h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                        href="#"
                      >
                        <img src={ilustracion} />
                        <div className="mb-2 mt-4 text-lg font-medium">
                          Plan para empresas
                        </div>
                        <p className="text-sm leading-tight  text-muted-foreground">
                          Pagina auto gestionable con un panel de administracion completo e intuitivo, sistema de compras y envios dentro de la web
                        </p>
                      </a>
                    </NavigationMenuLink>
                  </li>
                  <ListItem className="" href="/docs" title="Plan para emprendimientos">
                    Sitio web con un panel auto gestionable para tus productos , watshapp y contactos adentro de la web
                  </ListItem>

                  <ListItem href="/docs/installation" title="Plan para tu Portfolio">
                    Sitio web estatico, para que tengas tu carta de presentacion en linea y te publicites de una manera moderna.
                  </ListItem>
                  <ListItem href="/docs/primitives/typography" title="Plan web basico">
                    Sitio web basico, sin panel auto gestionable, con watshapp y contacto desde la web
                  </ListItem>
                </ul>
              </NavigationMenuContent>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>

        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuTrigger>Aplicaciones Mobiles</NavigationMenuTrigger>
              <NavigationMenuContent>
                <ul className="grid gap-3 p-6 w-full md:w-[400px] lg:w-[500px] grid-cols-[.75fr_1fr]">
                  <li className="row-span-3">
                    <NavigationMenuLink asChild>
                      <a
                        className="flex h-auto md:h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                        href="#"
                      >
                        <img className="h-[120px]" src={ilustracionMobile} />
                        <div className="mb-2 mt-4 text-lg font-medium">
                          Aplicacion para empresas
                        </div>
                        <p className="text-sm leading-tight  text-muted-foreground">
                          Aplicacion mobile auto gestionable con un panel de administracion completo e intuitivo, sistema de compras y envios dentro de la App
                        </p>
                      </a>
                    </NavigationMenuLink>
                  </li>
                  <ListItem className="" href="/docs" title="Aplicacion para emprendimientos">
                    Aplicacion mobile con un panel auto gestionable para tus productos , watshapp y contactos adentro de la app
                  </ListItem>

                  <ListItem href="/docs/primitives/typography" title="Aplicacion mobile basica">
                   Aplicacion mobile basica, sin panel auto gestionable, con watshapp y contacto desde la app
                  </ListItem>
                </ul>
              </NavigationMenuContent>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
      </nav>

      <div className="flex items-center justify-end w-full md:w-auto space-x-2">
        <div className="mr-2">
          <ModeToggle />
        </div>
        {open ? (
          <div className="block md:hidden #">
            <button onClick={(e) => setIsOpen(!open)} className="ml-4">
              <CloseIcon />
            </button>
          </div>
        ) : (

          <div className="block md:hidden #">
            <button onClick={(e) => setIsOpen(!open)} className="ml-4">
              <MenuIcon />
            </button>
          </div>
        )}

      </div>
    </header>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}


function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}

const ListItem = React.forwardRef<
  React.ElementRef<"a">,
  React.ComponentPropsWithoutRef<"a">
>(({ className, title, children, ...props }, ref) => {
  return (
    <li>
      <NavigationMenuLink asChild>
        <a
          ref={ref}
          className={cn(
            "block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground",
            className
          )}
          {...props}
        >
          <div className="text-sm font-medium leading-none">{title}</div>
          <p className=" text-sm line-clamp-4 leading-snug text-muted-foreground">
            {children}
          </p>
        </a>
      </NavigationMenuLink>
    </li>
  )
})
ListItem.displayName = "ListItem"